export const items = [
    {
        id: 1,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 2,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 3,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 70,
        total_capacity: 70,
    },
    {
        id: 4,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 5,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 6,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 7,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 70,
        total_capacity: 70,
    },
    {
        id: 8,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 10,
        total_capacity: 100,
    },
    {
        id: 9,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 10,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 11,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 100,
        total_capacity: 100,
    },
    {
        id: 12,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 13,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 70,
        total_capacity: 70,
    },
    {
        id: 14,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 100,
        total_capacity: 100,
    },
    {
        id: 15,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 16,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 17,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 18,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 19,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 20,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 21,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 22,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 23,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 24,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 25,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 26,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 27,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
    {
        id: 28,
        title: "Dribble",
        img: "/img/dribble.svg",
        date: "4 days ago",
        category: "Product",
        job_title: "Junior Product Designer-Singapore",
        capacity: 42,
        total_capacity: 70,
    },
    {
        id: 29,
        title: "Reddit",
        img: "/img/reddit.png",
        date: "2 days ago",
        category: "Design",
        job_title: "Software Architect Java - USA",
        capacity: 52,
        total_capacity: 100,
    },
    {
        id: 30,
        title: "Mailchimp",
        img: "/img/mailchimp.png",
        date: "1 day ago",
        category: "Design",
        job_title: "Senior Product Designer-Singapore",
        capacity: 32,
        total_capacity: 50,
    },
]